name: "Pull Request Labeler"
on:
- pull_request

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Label the PR
      uses: gerrymanoim/pr-prefix-labeler@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
